SR-PLUM/SidheRigel

Source/SidheRigel/Character/Cold/ColdCharacter.cpp, Source/SidheRigel/Character/Cold/ColdCharacter.h, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h, Source/SidheRigel/SidheRigelPlayerController.cpp
[Add] Implement LeftMouseButton Function
=> [Add] Implement LeftMouseButton Function

Source/SidheRigel/Character/Cold/ColdCharacter.cpp, Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.cpp, Source/SidheRigel/Character/Cold/Skill/ColdQProjectile.h, Source/SidheRigel/Character/Kerun/KerunAttackProjectile.cpp, Source/SidheRigel/Dummy/Dummy.cpp, Source/SidheRigel/Dummy/Dummy.h, Source/SidheRigel/Dummy/DummyProjectile.cpp, Source/SidheRigel/Dummy/DummyProjectile.h, Source/SidheRigel/Interface/Damagable.h, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
=> [Add] Implement LifeSteal

Source/SidheRigel/Dummy/Dummy.cpp, Source/SidheRigel/Dummy/Dummy.h, Source/SidheRigel/Dummy/DummyProjectile.cpp, Source/SidheRigel/Interface/Movable.h, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
[Add] Move Interface Implement (Knockback)
=> [Add] Move Interface Implement

Config/DefaultEngine.ini
[Debug] Steam Multiplay Host Debugging
=> [Debug] Steam Multiplay Host Debugging

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
=> [Add] Defence System

Source/SidheRigel/Enum/E_Character.h, Source/SidheRigel/UI/CharacterStatus.cpp, Source/SidheRigel/UI/CharacterStatus.h, Source/SidheRigel/UI/InGameUI.h
=> [Fix] Enum, Link Error

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelPlayerController.cpp, Source/SidheRigel/State/StateMachine.cpp, Source/SidheRigel/State/StateMachine.h, Source/SidheRigel/State/StopState.cpp, Source/SidheRigel/State/StopState.h, Source/SidheRigel/State/StunState.cpp, Source/SidheRigel/State/StunState.h
[Add] Implement Stun
##Merge to prevent conflicts that may occur during state refectoring
=> [Add] Implement Stun

Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/Minion/Minion.h, Source/SidheRigel/Tower/Tower.cpp
=> [Update] add MinionUI

Source/SidheRigel/State/StateMachine.cpp
=> Develop team attack error

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
[Fix] When Attack Enemy Character, Tower And Minion Attack AttackCharacter
=> [Fix] When Attack Enemy Character, Tower And Minion Attack AttackCharacter

Source/SidheRigel/Minion/Minion.cpp
[Fix] Move Minion Whne Delete Target
=> [Fix] Move Minion Whne Delete Target

Source/SidheRigel/SidheRigelCharacter.cpp
[Fix] add UpdateMoney function
=> [Fix] add UpdateMoney function

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h, Source/SidheRigel/State/DieState.cpp, Source/SidheRigel/State/DieState.h, Source/SidheRigel/State/StateMachine.cpp, Source/SidheRigel/State/StateMachine.h
=> [Add] Character Die State

Source/SidheRigel/Character/Cold/ColdCharacter.cpp, Source/SidheRigel/Character/TalentList.h, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
[Fix] FStruct Talent Pointer Error
=> [Fix] FStruct Talent Pointer Error

Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp, Source/SidheRigel/Character/Cold/Skill/ColdWProjectile.cpp
=> [Fix] Cant Damage TeamActor

Source/SidheRigel/State/AttackState.cpp
[Fix] Character Turn to Target When Attack
=> [Fix] Character Turn to Target When Attack

Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp, Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingRSkill.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h
=> Develop fairy wing

Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.cpp, Source/SidheRigel/Character/BlackWizard/BlackWizardCharacter.h, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardECollider.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardESkill.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQCollider.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQCollider.h, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardQSkill.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRCollider.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardRSkill.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardWSkill.cpp, Source/SidheRigel/Character/BlackWizard/Skill/BlackWizardWSkill.h
[Update] BlackWizard Skill Cant Damage TeamActor
=> [Update] BlackWizard Skill Cant Damage TeamActor

Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/Minion/Minion.h, Source/SidheRigel/Minion/MinionAIController.h
[Update] Minion Stop, Stun Implement
=> [Update] Minion Stop, Stun Implement

Source/SidheRigel/SidheRigelGameInstance.cpp
=> [Fix] Show Mouse Cursor

Source/SidheRigel/SidheRigelCharacter.cpp
[Update] bind ManaUI and bind HpUI in SetCurrentHp function
=> [Update] bind ManaUI and bind HpUI in SetCurrentHp function

Source/SidheRigel/Character/Skill.cpp, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/State/AttackState.cpp, Source/SidheRigel/State/AttackWaitState.cpp, Source/SidheRigel/State/IdleState.cpp, Source/SidheRigel/State/MoveState.cpp, Source/SidheRigel/State/MoveToAttackState.cpp, Source/SidheRigel/State/StunState.cpp, Source/SidheRigel/State/UseSkillState.cpp, Source/SidheRigel/Tower/Tower.cpp
=> [Debug] Remove Debug Log

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h, Source/SidheRigel/SidheRigelPlayerController.cpp, Source/SidheRigel/State/StateMachine.cpp, Source/SidheRigel/State/StateMachine.h
[Update] Change StateMachineTimer to FTimerHandle
=> [Update] Change StateMachineTimer to FTimerHandle

Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingEProjectile.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingESkill.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQSkill.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWSkill.h, Source/SidheRigel/Character/Skill.h, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
=> Develop fairy wing Talent

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
=> [Update] ReduceHeal

Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/Tower/Tower.cpp
[Fix] Minion, Tower Attack Damage 0 Bug
=> [Fix] Minion, Tower Attack Damage 0 Bug

Source/SidheRigel/State/UseSkillState.cpp
[Fix] When Kerun Use Q Skill, Get Correct Rotation
=> [Fix] When Kerun Use Q Skill, Get Correct Rotation

Source/SidheRigel/State/StateMachine.cpp
[Fix] Make Exception to PassiveSkill
=> [Fix] Make Exception to PassiveSkill

Source/SidheRigel/Lobby/LobbyGameMode.cpp, Source/SidheRigel/Lobby/LobbyGameMode.h, Source/SidheRigel/Lobby/LobbyPlayerController.cpp
=> [Fix] Can Enter Single

Source/SidheRigel/SidheRigelCamera.cpp, Source/SidheRigel/SidheRigelCamera.h
[Update] Increase CameraMoveAmount
=> [Update] Increase CameraMoveAmount

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelPlayerController.h, Source/SidheRigel/State/AttackWaitState.cpp
[Update] Change Stun Mechanism
=> [Update] Change Stun Mechanism

Source/SidheRigel/SidheRigelPlayerController.cpp, Source/SidheRigel/SidheRigelPlayerController.h
[Fix] StateMachine Update Error
=> [Fix] StateMachine Update Error

Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/Nexus/Nexus.cpp, Source/SidheRigel/Tower/Tower.cpp
[Update] Change Enemy HP Color
=> [Update] Change Enemy HP Color

Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/Tower/Tower.cpp
=> [Fix] minion, tower Target

Source/SidheRigel/Lobby/LobbyMenu.cpp, Source/SidheRigel/Lobby/LobbyPlayerController.cpp, Source/SidheRigel/Lobby/LobbyPlayerController.h
=> [Fix] None Character Error

Source/SidheRigel/Character/FairyWing/Skill/FairyWingRCollider.cpp
=> [Fix] FairyWing R Skill Bug

Source/SidheRigel/Dummy/DummyProjectile.cpp
=> [Fix] ProjectileRemain Bug

Source/SidheRigel/Minion/MinionSpawner.cpp, Source/SidheRigel/Minion/MinionSpawner.h
=> Develop delay minion spawn

Config/DefaultInput.ini, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelPlayerController.cpp, Source/SidheRigel/SidheRigelPlayerController.h, Source/SidheRigel/State/AttackState.cpp, Source/SidheRigel/State/AttackWaitState.cpp, Source/SidheRigel/State/IdleState.cpp, Source/SidheRigel/State/MoveState.cpp, Source/SidheRigel/State/MoveToAttackState.cpp
=> [Add] Attack Use A Button

Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp, Source/SidheRigel/Character/AI/AISidheRigelCharacter.h
=> [Add] AI Dead State

Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp, Source/SidheRigel/Character/Cold/ColdCharacter.cpp, Source/SidheRigel/Character/Cold/ColdCharacter.h, Source/SidheRigel/Character/Cold/Skill/ColdESkill.cpp, Source/SidheRigel/Character/Cold/Skill/ColdESkill.h, Source/SidheRigel/Character/Cold/Skill/ColdQSkill.cpp, Source/SidheRigel/Character/Cold/Skill/ColdQSkill.h, Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.cpp, Source/SidheRigel/Character/Cold/Skill/ColdR2Skill.h, Source/SidheRigel/Character/Cold/Skill/ColdWSkill.cpp, Source/SidheRigel/Character/Cold/Skill/ColdWSkill.h, Source/SidheRigel/Character/FairyWing/FairyWingCharacter.cpp, Source/SidheRigel/Character/FairyWing/FairyWingCharacter.h, Source/SidheRigel/Character/FairyWing/Skill/FairyWingQCollider.cpp, Source/SidheRigel/Character/FairyWing/Skill/FairyWingWCollider.cpp, Source/SidheRigel/Character/Kerun/KerunCharacter.cpp, Source/SidheRigel/Character/Kerun/KerunCharacter.h, Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp, Source/SidheRigel/Character/Kerun/Skills/KerunR1Skill.cpp, Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.cpp, Source/SidheRigel/Character/Kerun/Skills/KerunWSkill.h, Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/Minion/RangeMinion.cpp, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h, Source/SidheRigel/Tower/Tower.h
=> Develop character balancing

Source/SidheRigel/Character/Skill.cpp
[Fix] Can Use Ult When Level 10
=> [Fix] Can Use Ult When Level 10

Source/SidheRigel/SidheRigelPlayerController.cpp
[Fix] Cant Move Continuous When Using Skill With Move
=> [Fix] Cant Move Continuous When Using Skill With Move

Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp
=> [Fix] AI Attack Nexus

Source/SidheRigel/Minion/Minion.cpp, Source/SidheRigel/SidheRigelCharacter.cpp
[Fix] Add Range When Attack Nexus
=> [Fix] Add Range When Attack Nexus

Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h, Source/SidheRigel/State/DieState.cpp
=> [Fix] Mana Restore When dead

Source/SidheRigel/Character/Kerun/KerunCharacter.cpp, Source/SidheRigel/Character/Kerun/KerunCharacter.h, Source/SidheRigel/Character/Kerun/Skills/KerunQSkill.cpp, Source/SidheRigel/Dummy/DummyProjectile.cpp, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h, Source/SidheRigel/Tower/Tower.cpp
[Fix] Kerun Balancing, Bug Fix
=> [Fix] Kerun Balancing, Bug Fix

Source/SidheRigel/Character/AI/AISidheRigelCharacter.cpp, Source/SidheRigel/Nexus/Nexus.cpp, Source/SidheRigel/Nexus/Nexus.h, Source/SidheRigel/Tower/Tower.cpp
=> Develop fix nexus range bug

Source/SidheRigel/Character/Cold/Skill/ColdEDamageField.cpp, Source/SidheRigel/SidheRigelCharacter.cpp, Source/SidheRigel/SidheRigelCharacter.h
=> [Add] add Execute function
